# Generated by Django 3.0 on 2019-12-18 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='key_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chave',
                'verbose_name_plural': 'chaves',
            },
        ),
    ]
